### ISSUE TITLE
Ancestor onTap Event Not Triggered  When Clicking SimpleSheetMusic Image

### ISSUE THREAD

**Issue by beattizzle** [tomoyu719/simple_sheet_music#25]
Discovered a bug where tapping a SimpleSheetMusic image ignores the ancestors' onTap event due to the GestureDetector's empty onTap function inside the SimpleSheetMusicState class.  I propose removing the GestureDetector altogether.  It appears to have been used previously for testing, but now has no functionality attached to it.

**Comment by lukasnalezenec** [comment]
It makes sense. 
My two cents: I would recommend to reimplement this top level class in your app.

**Comment by beattizzle** [comment]
I don't understand your recommendation.  Why do I need to reimplement it?
