### ISSUE TITLE
[feature request] Harmony

### ISSUE THREAD

**Issue by heyaphra** [tomoyu719/simple_sheet_music#5]
Nice declarative solution to the tricky problem of programmatic music engraving! I think it would be valuable to add the ability to render chords. If you have an idea on how this could be done, feel free to share and I could try and attempt to help if needed on a forked version of the repo.

**Comment by tomoyu719** [comment]
We were not sure which music symbols were in demand, so your request would be very helpful. We will give priority to the implementation of chords.

**Comment by heyaphra** [comment]
Great! Just to clarify, by chords I mean multiple notes stacked vertically with chord symbols being a "nice-to-have" in this case. Thanks!
